In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Show all columns when printing
pd.set_option('display.max_columns', None)

In [2]:
from src.db_connect import RedshiftClient

In [3]:
rds_connect = RedshiftClient()

In [4]:
data = rds_connect.run_query('account_balances.sql', mode="training")

/Users/ilya.katliarou/Documents/CCF/src/db_connect.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.conn)

In [5]:
data.head()

,user_id,reference_date,ab__avg_bal_3m,ab__avg_bal_change_3m,ab__max_util_3m,ab__max_bal_change_3m,ab__std_util_3m,ab__std_bal_change_3m,ab__bal_changed_3m,ab__bal_change_freq_3m,ab__mean_abs_change_6m,ab__std_abs_change_6m,ab__max_one_day_drop_6m,ab__inflow_spike_count_6m,ab__days_down_6m,ab__near_zero_days_6m
0,085f27aa-5d6b-4c7d-a172-4ba64f7961f5,2023-11-13,488.770440,479.575495,1746.49,404.18,523.952923,21.063642,1,67,47.209337,192.317662,-500.49,3,73,31
1,09c9de10-192b-4425-8c5d-31ba80488ed1,2022-10-31,-244.863077,-17.159667,-89.15,-165.35,24.137572,-36.198786,1,17,12.567624,27.249802,-134.14,0,45,6
2,12726365-40f2-431e-bcf0-2ec0590c6061,2024-07-19,-631.539011,-21.225000,-445.54,-9.32,36.539594,8.581419,1,10,11.258453,36.315580,-212.06,1,40,11
3,1f2c6583-50c2-477a-982a-9edf7ba6b0f4,2024-09-22,499.410110,83.440495,2613.98,1533.88,412.754743,280.357579,1,86,183.221436,323.757742,-1484.66,19,126,1
4,20305c54-b4ad-422c-95ed-7425266ef52a,2025-01-19,180.719011,-233.898269,1040.21,-559.87,236.591383,-211.948529,1,28,144.743149,402.098573,-2556.55,7,56,6

In [7]:
# Step 1: import the class
from src.data_collection import DataCollector

# Step 2: initialize the collector
collector = DataCollector(mode="training")  # mode can be "training" or "inference"

# Step 3: run the full pipeline (collect + merge)
merged_df = collector.run()

print(merged_df.shape)
merged_df.head()

Running: model_versions.sql
Saved: src/data/training/raw/model_versions.csv
Running: sample.sql
Saved: src/data/training/raw/sample.csv
Running: dynamic_user_data.sql
Saved: src/data/training/raw/dynamic_user_data.csv
Running: madrid.sql
Saved: src/data/training/raw/madrid.csv
Running: user_lifecycle.sql
Saved: src/data/training/raw/user_lifecycle.csv
Running: overdraft_balances.sql
Saved: src/data/training/raw/overdraft_balances.csv
Running: account_balances.sql
Saved: src/data/training/raw/account_balances.csv
Running: dunning.sql
Saved: src/data/training/raw/dunning.csv
Running: credit_bureau.sql
Saved: src/data/training/raw/credit_bureau.csv
Running: existing_products.sql
Saved: src/data/training/raw/existing_products.csv
Merged dataset saved to src/data/training/raw/merged_training_data.csv (shape: (15211, 76))
Connection closed.
(15211, 76)

,user_id,reference_date,default_date,ob__limit_ref,ob__balance_ref,ob__avg_util_ref,ob__open_limit_ref,t__is_drawn,t__ccf,mv__is_lisbon_v1,mv__is_lisbon_v2,mv__is_lisbon_v3,mv__is_lisbon_v4,mv__is_porto_v1,mv__is_porto_v2,ef__is_covid,gender,nationality,sd__age,sd__age_since_first_kyc,sd__age_since_last_kyc,sd__membership_product,sd__max_daily_logins_6m,sd__max_daily_logins_12m,madrid__avg_monthly_salary_3m,madrid__avg_monthly_expenses_3m,madrid__avg_monthly_repayment_capacity_3m,ul__is_expat,od__history_length_days,od__is_history,ob__avg_util_3m,ob__avg_util_change_3m,ob__max_util_3m,ob__max_util_change_3m,ob__std_util_3m,ob__std_util_change_3m,ob__util_slope_3m,ob__util_range_3m,ob__num_od_entries_6m,ob__num_od_exits_6m,ob__overlimit_days_6m,ob__full_repayment_events_6m,ob__max_consecutive_od_days_since_creation_ratio,ob__od_draw_days_6m,ob__od_enabled_zero_util_days_6m,ob__technical_od_days_6m,ob__technical_od_deep_days_6m,ob__avg_util_first_2m_since_creation,ob__avg_util_change_last2m_to_first2m,ob__avg_util_first2m_1y,ob__avg_util_change_last2m_to_first2m_1y,ob__max_consecutive_overlimit_days_since_creation_ratio,ob__partial_repayment_events_6m,ob__full_repayment_change_3m_vs_prev_3m,ob__util_last2m_to_first2m_ratio,ob__util_last2m_to_first2m_1y_ratio,ob__max_to_avg_util_3m_ratio,ab__avg_bal_3m,ab__avg_bal_change_3m,ab__max_util_3m,ab__max_bal_change_3m,ab__std_util_3m,ab__std_bal_change_3m,ab__bal_changed_3m,ab__bal_change_freq_3m,ab__mean_abs_change_6m,ab__std_abs_change_6m,ab__max_one_day_drop_6m,ab__inflow_spike_count_6m,ab__days_down_6m,ab__near_zero_days_6m,dn__recent_action,dn__max_action_level,cb__most_recent_score,cb__worst_score,ep__cc_tbil_balance
0,0137ff64-6145-4def-9274-032fb57695ee,2022-04-07,2023-03-27,500.0,0.00,0.00000,1.00000,1,0.59844,1,0,0,0,0,0,0,MALE,DEU,23,296.0,296.0,PERSONAL_FLEX,13.0,23.0,746.740000,5829.990000,5766.580000,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,0,0,NaN,0,0,0,0,NaN,NaN,NaN,NaN,NaN,0,0,NaN,NaN,NaN,637.590769,-521.970118,2805.56,-1694.84,608.785472,-311.479807,1,74,293.957624,471.505290,-2439.31,30,103,3,NaN,NaN,M,P,0.00
1,0248da13-29cc-4025-9c62-ea3b1d7ec671,2023-03-30,2024-03-29,5000.0,2744.94,0.54899,0.45101,1,1.00000,1,0,0,0,0,0,0,MALE,IND,29,918.0,918.0,PERSONAL_STANDARD,5.0,6.0,2095.480000,1218.486667,2361.893333,1,537,1,0.894264,-0.054008,0.999760,0.000732,0.093225,0.046960,-6.166757e-10,0.450772,0,0,0,0,0.0,181,0,0,0,0.129030,0.753482,0.427469,0.455043,NaN,12,0,6.8395,2.0645,1.1179,-4471.324396,270.038903,-2744.94,1277.44,466.123292,234.802303,1,45,118.856796,322.304930,-1365.28,9,70,0,NaN,NaN,F,F,0.00
2,051f21a3-e551-4147-b0d7-4b1af3caf194,2019-07-08,2019-09-17,3000.0,2939.02,0.97967,0.02033,0,0.00000,1,0,0,0,0,0,0,MALE,DEU,18,160.0,160.0,PERSONAL_STANDARD,20.0,20.0,980.726667,194.050000,994.060000,0,158,1,0.967663,-0.033812,1.014516,-0.010353,0.085015,-0.029115,-6.984690e-09,0.325420,0,0,61,0,1.0,158,0,0,0,0.979673,-0.009746,NaN,NaN,0.0,9,0,0.9900,NaN,1.0484,-2880.353736,167.888742,-1949.14,118.15,291.348890,-14.350513,1,28,79.520375,210.592120,-1000.00,5,56,3,90.0,90.0,M,M,0.00
3,06354e33-ec7a-44f1-90a1-96a39837d97d,2024-09-27,2024-11-05,500.0,0.00,0.00000,1.00000,1,0.98658,0,0,0,0,0,1,0,MALE,DEU,47,1627.0,1627.0,PERSONAL_FLEX,16.0,16.0,177.413333,814.353333,916.796667,0,1,1,0.000000,NaN,0.000000,NaN,NaN,NaN,0.000000e+00,0.000000,0,0,0,0,NaN,0,1,0,0,0.000000,0.000000,NaN,NaN,NaN,0,0,NaN,NaN,NaN,233.006593,87.014075,668.23,407.27,134.296088,65.825942,1,42,47.577072,91.816230,-500.49,6,64,0,NaN,NaN,M,P,610.65
4,1019c497-a45e-4224-85eb-4006d94bc786,2021-12-11,2022-12-11,250.0,242.54,0.97016,0.02984,1,1.00000,1,0,0,0,0,0,1,MALE,HRV,40,663.0,663.0,BUSINESS_YOU,2.0,2.0,0.000000,0.000000,14.000000,1,664,1,1.019552,-0.024164,1.058960,-0.028800,0.026153,0.003689,-4.291050e-09,0.088800,0,0,72,0,0.0,181,0,0,0,0.761342,0.254398,1.024801,-0.009061,0.0,4,0,1.3341,0.9911,1.0386,-254.888132,6.040839,-242.54,6.86,6.538270,0.922193,1,7,0.814751,3.611862,-9.90,0,8,0,1.0,10.0,E,E,0.00

In [8]:
from src.data_processing import TrainingDataProcessor
processor = TrainingDataProcessor()
df_processed = processor.process()

Loading data...
Identifying variable types...
Encoding categorical variables...
Saving processed dataset to src/data/training/processed/final_training_data.csv...
Processing complete.

### Note: Data processing pipeline is only applicable to CCF_v1.ipynb

In [9]:
df = pd.read_csv("src/data/training/raw/merged_training_data.csv")

In [10]:
df.to_parquet("src/data/training/raw/merged_training_data.parquet", index=False)

In [11]:
tmerged_df = pd.read_csv("src/data/training/processed/final_training_data.csv")

In [12]:
tmerged_df.shape

(15211, 76)