In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Show all columns when printing
pd.set_option('display.max_columns', None)

In [2]:
from src.db_connect import RedshiftClient

In [3]:
rds_connect = RedshiftClient()

In [4]:
data = rds_connect.run_query('account_balances.sql', mode="training")

/Users/ilya.katliarou/Documents/CCF/src/db_connect.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.conn)

In [25]:
data.head()

,user_id,reference_date,ab__avg_bal_3m,ab__avg_bal_change_3m,ab__max_util_3m,ab__max_bal_change_3m,ab__std_util_3m,ab__std_bal_change_3m,ab__bal_changed_3m,ab__bal_change_freq_3m,ab__mean_abs_change_6m,ab__std_abs_change_6m,ab__max_one_day_drop_6m,ab__inflow_spike_count_6m,ab__days_down_6m,ab__near_zero_days_6m
0,085f27aa-5d6b-4c7d-a172-4ba64f7961f5,2023-11-13,488.770440,479.575495,1746.49,404.18,523.952923,21.063642,1,67,47.209337,192.317662,-500.49,3,73,31
1,09c9de10-192b-4425-8c5d-31ba80488ed1,2022-10-31,-244.863077,-17.159667,-89.15,-165.35,24.137572,-36.198786,1,17,12.567624,27.249802,-134.14,0,45,6
2,12726365-40f2-431e-bcf0-2ec0590c6061,2024-07-19,-631.539011,-21.225000,-445.54,-9.32,36.539594,8.581419,1,10,11.258453,36.315580,-212.06,1,40,11
3,1f2c6583-50c2-477a-982a-9edf7ba6b0f4,2024-09-22,499.410110,83.440495,2613.98,1533.88,412.754743,280.357579,1,86,183.221436,323.757742,-1484.66,19,126,1
4,20305c54-b4ad-422c-95ed-7425266ef52a,2025-01-19,180.719011,-233.898269,1040.21,-559.87,236.591383,-211.948529,1,28,144.743149,402.098573,-2556.55,7,56,6

In [4]:
# Step 1: import the class
from src.data_collection import DataCollector

# Step 2: initialize the collector
collector = DataCollector(mode="inference")  # mode can be "training" or "inference"

# Step 3: run the full pipeline (collect + merge)
merged_df = collector.run()

print(merged_df.shape)
merged_df.head()

Running: sample.sql

/Users/ilya.katliarou/Documents/CCF/src/db_connect.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.conn)

Saved: src/data/inference/raw/sample.csv
Running: dynamic_user_data.sql
Saved: src/data/inference/raw/dynamic_user_data.csv
Running: overdraft_balances.sql
Saved: src/data/inference/raw/overdraft_balances.csv
Running: account_balances.sql
Saved: src/data/inference/raw/account_balances.csv
Running: credit_bureau.sql
Saved: src/data/inference/raw/credit_bureau.csv
Merged dataset saved to src/data/inference/raw/merged_inference_data.csv (shape: (188391, 59))
Connection closed.
(188391, 59)

,user_id,reference_date,ob__limit_ref,ob__balance_ref,ob__open_limit_ref,ob__avg_util_ref,gender,nationality,sd__age,sd__age_since_first_kyc,sd__age_since_last_kyc,sd__membership_product,sd__max_daily_logins_6m,sd__max_daily_logins_12m,od__history_length_days,od__is_history,ob__avg_util_3m,ob__avg_util_change_3m,ob__max_util_3m,ob__max_util_change_3m,ob__std_util_3m,ob__std_util_change_3m,ob__util_slope_3m,ob__util_range_3m,ob__num_od_entries_6m,ob__num_od_exits_6m,ob__overlimit_days_6m,ob__full_repayment_events_6m,ob__max_consecutive_od_days_since_creation_ratio,ob__od_draw_days_6m,ob__od_enabled_zero_util_days_6m,ob__technical_od_days_6m,ob__technical_od_deep_days_6m,ob__avg_util_first_2m_since_creation,ob__avg_util_change_last2m_to_first2m,ob__avg_util_first2m_1y,ob__avg_util_change_last2m_to_first2m_1y,ob__max_consecutive_overlimit_days_since_creation_ratio,ob__partial_repayment_events_6m,ob__full_repayment_change_3m_vs_prev_3m,ob__util_last2m_to_first2m_ratio,ob__util_last2m_to_first2m_1y_ratio,ob__max_to_avg_util_3m_ratio,ab__avg_bal_3m,ab__avg_bal_change_3m,ab__max_util_3m,ab__max_bal_change_3m,ab__std_util_3m,ab__std_bal_change_3m,ab__bal_changed_3m,ab__bal_change_freq_3m,ab__mean_abs_change_6m,ab__std_abs_change_6m,ab__max_one_day_drop_6m,ab__inflow_spike_count_6m,ab__days_down_6m,ab__near_zero_days_6m,cb__most_recent_score,cb__worst_score
0,2dc8f812-d874-46ab-9cf0-77a5d0eb1fec,2026-09-30,250.0,55.20,0.779200,0.220800,FEMALE,DEU,37,2965.0,2965.0,BUSINESS_STANDARD,1.0,1.0,2966,1,0.098303,0.044567,0.620000,-0.39920,0.168813,-0.159696,1.694965e-08,0.620000,3,2,0,2,0.0,57,124,0,0,0.000000,0.085665,0.000000,0.085665,NaN,2,0,NaN,NaN,6.3070,17.242527,-93.939505,128.54,-98.35,78.188536,-76.888995,1,7,5.538177,32.056338,-275.50,0,7,29,D,F
1,2dd3bd0b-aecc-4897-8b6d-c0d035e1d8e0,2026-09-30,1000.0,366.56,0.633440,0.366560,FEMALE,DEU,37,2250.0,2250.0,BUSINESS_SMART,14.0,14.0,353,1,0.481322,NaN,0.832350,NaN,0.272624,NaN,3.361605e-07,0.832350,1,0,0,0,0.0,8,1,2,2,0.101197,0.380125,0.626904,-0.145582,0.0,2,0,4.7562,0.7677,1.7292,436.400769,-596.116914,6087.57,-5080.09,992.532906,-1082.161306,1,70,373.742431,1026.504316,-5636.81,24,115,19,C,O
2,2ddab898-e361-4b50-aaf0-d4148122ae5d,2026-09-30,3250.0,2220.29,0.316833,0.683166,MALE,DEU,28,3192.0,3192.0,PERSONAL_METAL,3.0,5.0,3193,1,0.179550,0.196951,0.683166,0.33097,0.167393,0.087038,4.347616e-08,0.683166,3,3,0,3,0.0,150,31,0,0,0.000000,0.235995,0.090022,0.145973,NaN,9,-1,NaN,2.6215,3.8048,-538.730440,-776.016097,431.64,-744.53,599.110285,194.555952,1,68,71.420608,193.022421,-1093.08,10,106,4,B,C
3,2df3447b-e886-42a3-81e2-6d4e673809e8,2026-09-30,250.0,0.27,0.998920,0.001080,MALE,SWE,46,3487.0,3487.0,PERSONAL_STANDARD,NaN,NaN,2871,1,0.001040,0.000001,0.001080,0.00004,0.000004,0.000007,1.528169e-10,0.000040,0,0,0,0,0.0,181,0,0,0,0.010828,-0.009788,0.000916,0.000124,NaN,0,0,0.0960,1.1353,1.0384,-0.260110,-0.000323,-0.26,0.00,0.001048,0.001796,1,1,0.000110,0.001048,-0.01,0,2,181,G,M
4,2e062097-8f86-4653-a016-7453e25c92c2,2026-09-30,250.0,107.62,0.569520,0.430480,MALE,DEU,34,2046.0,2046.0,PERSONAL_STANDARD,NaN,1.0,657,1,0.416673,0.000450,0.430480,0.01396,0.001463,0.002507,2.568447e-10,0.013960,0,0,0,0,0.0,181,0,0,0,0.011023,0.405725,0.376113,0.040635,NaN,1,0,37.8071,1.1080,1.0331,-104.168352,-0.112581,-104.13,0.00,0.365851,0.626823,1,1,0.037901,0.359606,-3.49,0,2,0,D,D

In [5]:
merged_df['user_id'].nunique()

188391

In [8]:
from src.data_processing import TrainingDataProcessor
processor = TrainingDataProcessor()
df_processed = processor.process()

Loading data...
Identifying variable types...
Encoding categorical variables...
Saving processed dataset to src/data/training/processed/final_training_data.csv...
Processing complete.

### Note: Data processing pipeline is only applicable to CCF_v1.ipynb

In [9]:
df = pd.read_csv("src/data/training/raw/merged_training_data.csv")

In [10]:
df.to_parquet("src/data/training/raw/merged_training_data.parquet", index=False)

In [11]:
tmerged_df = pd.read_csv("src/data/training/processed/final_training_data.csv")

In [12]:
tmerged_df.shape

(15211, 76)