In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Show all columns when printing
pd.set_option('display.max_columns', None)

In [2]:
from src.db_connect import RedshiftClient

In [3]:
rds_connect = RedshiftClient()

In [ ]:
data = rds_connect.run_query('overdraft_balances.sql', mode="training")

/Users/ilya.katliarou/Documents/CCF/src/db_connect.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.conn)

In [6]:
data.head()

,user_id,reference_date,creation_date,od__history_length_days,od__is_history,ob__avg_util_3m,ob__avg_util_change_3m,ob__max_util_3m,ob__max_util_change_3m,ob__std_util_3m,...,ob__avg_util_first_2m,ob__avg_util_change_since_orig,ob__avg_util_1y_ago,ob__avg_util_change_1y,ob__max_consecutive_overlimit_days_6m,ob__partial_repayment_days_6m,ob__full_repayment_change_3m_vs_prev_3m,ob__util_last2m_to_first2m_ratio,ob__util_last2m_to_first2m_1y_ratio,ob__max_to_avg_util_3m_ratio
0,006f1f9b-4355-4850-b278-5c728a3ba539,2022-11-22,2018-09-12,1533,1,0.007660,NaN,0.007660,NaN,0.000000,...,0.479548,-0.471888,0.161818,-0.154158,0,142,0,0.0159,0.0473,1.0000
1,0101e84c-7480-41d4-b47e-8bbf8beb0780,2023-02-01,2018-04-04,1765,1,0.923106,0.024943,0.939004,0.024943,0.012058,...,NaN,NaN,0.854591,0.072963,0,181,0,NaN,1.0853,1.0172
2,0367f40f-94ac-468e-955b-029464f77d55,2024-07-10,2023-01-14,544,1,1.003564,-0.064204,1.064880,-0.004980,0.081220,...,0.832425,0.157053,0.751548,0.237930,140,68,0,1.1886,1.3165,1.0610
3,06eadd92-372d-40df-93bc-5ccfde181a16,2022-09-29,2022-04-08,175,1,0.449990,0.034640,0.998720,0.051240,0.192998,...,0.001880,0.490966,NaN,NaN,0,94,0,262.1521,NaN,2.2194
4,0aa06778-70d6-4f39-a2cb-9f6530a30950,2023-05-15,2020-01-24,1208,1,0.794927,0.022333,0.805971,0.022333,0.011228,...,0.911506,-0.111027,0.716619,0.083860,0,181,0,0.8781,1.1170,1.0138

In [2]:
# Step 1: import the class
from src.data_collection import DataCollector

# Step 2: initialize the collector
collector = DataCollector(mode="inference")  # mode can be "training" or "inference"

# Step 3: run the full pipeline (collect + merge)
merged_df = collector.run()

print(merged_df.shape)
merged_df.head()

Running: model_versions.sql

/Users/ilya.katliarou/Documents/CCF/src/db_connect.py:44: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, self.conn)

Saved: src/data/inference/raw/model_versions.csv
Running: sample.sql
Saved: src/data/inference/raw/sample.csv
Running: dynamic_user_data.sql
Saved: src/data/inference/raw/dynamic_user_data.csv
Running: madrid.sql
Saved: src/data/inference/raw/madrid.csv
Running: user_lifecycle.sql
Saved: src/data/inference/raw/user_lifecycle.csv
Running: overdraft_balances.sql
Saved: src/data/inference/raw/overdraft_balances.csv
Running: account_balances.sql
Saved: src/data/inference/raw/account_balances.csv
Running: dunning.sql
Saved: src/data/inference/raw/dunning.csv
Running: credit_bureau.sql
Saved: src/data/inference/raw/credit_bureau.csv
Running: existing_products.sql
Saved: src/data/inference/raw/existing_products.csv
Merged dataset saved to src/data/inference/raw/merged_inference_data.csv (shape: (168496, 73))
Connection closed.
(168496, 73)

,user_id,reference_date,ob__limit_ref,ob__balance_ref,ob__open_limit_ref,ob__avg_util_ref,mv__is_lisbon_v1,mv__is_lisbon_v2,mv__is_lisbon_v3,mv__is_lisbon_v4,...,ab__std_abs_change_6m,ab__max_one_day_drop_6m,ab__inflow_spike_count_6m,ab__days_down_6m,ab__near_zero_days_6m,dn__recent_action,dn__max_action_level,cb__most_recent_score,cb__worst_score,ep__cc_tbil_balance
0,15290ec6-09c3-4e11-b28f-40e0ca4886f7,2026-02-28,3750.0,0.00,1.00000,0.00000,1,0,0,0,...,154.880539,-1833.18,7,45,0,NaN,NaN,F,F,0.00
1,1587a2dc-c0b0-4120-8002-0c1cde9211fa,2026-02-28,8000.0,0.00,1.00000,0.00000,1,0,0,0,...,160.409956,-536.78,5,78,0,NaN,NaN,C,M,1473.87
2,15ad0b22-759c-41e2-8036-01012299aee4,2026-02-28,500.0,476.69,0.04662,0.95338,0,0,0,0,...,91.446890,-367.09,8,46,2,NaN,NaN,M,M,4407.33
3,16e500cb-26e5-409b-b7eb-a963e1235bc7,2026-02-28,250.0,0.00,1.00000,0.00000,1,0,0,0,...,0.000000,0.00,0,0,181,NaN,NaN,D,G,0.00
4,17061379-646d-4e63-a919-62dfc64d8930,2026-02-28,500.0,508.22,0.00000,1.01644,1,0,0,0,...,2.218496,-16.35,0,7,0,NaN,NaN,E,E,0.00

In [1]:
from src.data_processing import TrainingDataProcessor
processor = TrainingDataProcessor()
df_processed = processor.process()

Loading data...
Identifying variable types...
Encoding categorical variables...
Saving processed dataset to src/data/training/processed/final_training_data.csv...
Processing complete.

In [3]:
df = pd.read_csv("src/data/training/raw/merged_training_data.csv")

In [5]:
df.to_parquet("src/data/training/raw/merged_training_data.parquet", index=False)

In [8]:
tmerged_df = pd.read_csv("src/data/training/processed/final_training_data.csv")

In [9]:
tmerged_df.shape

(15534, 75)