In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
import pickle
from sklearn.preprocessing import OrdinalEncoder

In [2]:
df = pd.read_csv("src/data/inference/raw/merged_inference_data.csv")

In [3]:
user_ids = df['user_id']

In [4]:
df["mix__sd_od_history_to_kyc_ratio"] = df["od__history_length_days"] / df["sd__age_since_first_kyc"]

In [5]:
ordinal_features = [
    "cb__worst_score",
    "sd__membership_product"
]

ordinal_encoder = OrdinalEncoder(
    categories=[
        # example – replace with your actual order
        ["A", "B", "C", "D", "E", "F", "G", "M", "N", "O", "P", np.nan],           # cb__worst_score
        ["PERSONAL_FLEX", "PERSONAL_STANDARD", "PERSONAL_SMART"
         , "PERSONAL_YOU", "PERSONAL_METAL", "BUSINESS_STANDARD"
         , "BUSINESS_SMART", "BUSINESS_YOU", "BUSINESS_METAL", np.nan]        # sd__membership_product
    ]
)

df[ordinal_features] = ordinal_encoder.fit_transform(
    df[ordinal_features]
)

In [6]:
with open("xgb_reg_ccf.pkl", "rb") as f:
    model_artifact = pickle.load(f)

best_reg_model = model_artifact["model"]

In [7]:
reg_features = best_reg_model.get_booster().feature_names

X_reg = df[reg_features]

In [8]:
def predict_ccf(X, best_reg_model, upper_clipping_limit=1.0, bottom_clipping_limit=0.0):
    """
    Applies model to predict CCF for new data.
    """
    reg_predictions = best_reg_model.predict(X)
    final_values = np.clip(reg_predictions, a_min=bottom_clipping_limit, a_max=upper_clipping_limit)
        
    return final_values

In [9]:
df["ccf"] = predict_ccf(
    X=X_reg,
    best_reg_model=best_reg_model,
    upper_clipping_limit=1.0,
    bottom_clipping_limit=0.0
)

In [11]:
df

,user_id,reference_date,ob__limit_ref,ob__balance_ref,ob__open_limit_ref,ob__avg_util_ref,gender,nationality,sd__age,sd__age_since_first_kyc,...,ab__mean_abs_change_6m,ab__std_abs_change_6m,ab__max_one_day_drop_6m,ab__inflow_spike_count_6m,ab__days_down_6m,ab__near_zero_days_6m,cb__most_recent_score,cb__worst_score,mix__sd_od_history_to_kyc_ratio,ccf
0,2dc8f812-d874-46ab-9cf0-77a5d0eb1fec,2026-09-30,250.0,55.20,0.779200,0.220800,FEMALE,DEU,37,2965.0,...,5.538177,32.056338,-275.50,0,7,29,D,5.0,1.000337,0.378921
1,2dd3bd0b-aecc-4897-8b6d-c0d035e1d8e0,2026-09-30,1000.0,366.56,0.633440,0.366560,FEMALE,DEU,37,2250.0,...,373.742431,1026.504316,-5636.81,24,115,19,C,9.0,0.156889,0.491168
2,2ddab898-e361-4b50-aaf0-d4148122ae5d,2026-09-30,3250.0,2220.29,0.316833,0.683166,MALE,DEU,28,3192.0,...,71.420608,193.022421,-1093.08,10,106,4,B,2.0,1.000313,0.612073
3,2df3447b-e886-42a3-81e2-6d4e673809e8,2026-09-30,250.0,0.27,0.998920,0.001080,MALE,SWE,46,3487.0,...,0.000110,0.001048,-0.01,0,2,181,G,7.0,0.823344,0.320777
4,2e062097-8f86-4653-a016-7453e25c92c2,2026-09-30,250.0,107.62,0.569520,0.430480,MALE,DEU,34,2046.0,...,0.037901,0.359606,-3.49,0,2,0,D,3.0,0.321114,0.416047
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
188386,2260d729-f7c5-4c87-b794-c43f87d877a0,2026-09-30,1126.0,0.00,1.000000,0.000000,MALE,DEU,24,2282.0,...,18.600552,62.229764,-587.93,6,72,0,F,5.0,0.102542,0.389849
188387,228c5a04-a173-4376-b68c-27d11dbf12df,2026-09-30,5405.0,0.00,1.000000,0.000000,MALE,DEU,31,1213.0,...,264.430055,876.643796,-1347.91,10,157,0,D,7.0,0.148392,0.690934
188388,228c95b9-9cfd-42a2-9bf2-9400eda5200f,2026-09-30,1200.0,0.00,1.000000,0.000000,MALE,AUT,33,2699.0,...,50.946409,138.511046,-1000.00,9,100,29,E,7.0,0.355687,0.598780
188389,22e35f50-cd89-4e8a-9a42-d59ee26996ec,2026-09-30,3000.0,0.00,1.000000,0.000000,MALE,DEU,44,3141.0,...,20.876077,137.206923,-947.98,2,3,0,B,1.0,1.000318,0.227463
188390,22ed8f9f-ace9-4330-ae81-05134a158ae4,2026-09-30,1000.0,0.00,1.000000,0.000000,MALE,DEU,36,777.0,...,324.729669,732.998082,-2095.67,22,136,9,G,6.0,0.202059,0.487404

In [12]:
final_df = df[['user_id', 'reference_date', 'ccf']]

In [13]:
final_df.to_csv("ccf__output_30.09.2026.csv", index=False)

In [14]:
df['ccf'].mean()

np.float32(0.40670153)

In [16]:
final_df[final_df['ccf'] < 0.1]

                                     user_id reference_date       ccf
28      3259266a-6c7e-447c-aea8-6367c81dccb0     2026-09-30  0.073103
116     436288c7-ed45-4dfe-8b93-570322860e00     2026-09-30  0.085896
155     4b7760e4-1272-4506-a8bd-e5a7a95b4081     2026-09-30  0.066349
176     4e19c6dd-bda1-4ba2-a7c0-df39ddd872af     2026-09-30  0.080787
177     4e3cb904-d54d-4a41-8929-95556c3ae5a8     2026-09-30  0.091350
...                                      ...            ...       ...
188266  159f7a79-0b06-48e8-aded-cb80f16486ee     2026-09-30  0.094096
188271  162a2ddc-d0a9-469c-afef-104cd38db2b7     2026-09-30  0.067014
188309  2a4c0407-9204-43e1-bb81-24b950bfa209     2026-09-30  0.063739
188316  2b2cbd5b-55a3-46ca-a03f-b4628dff89b9     2026-09-30  0.065658
188372  1f0a7f9a-38a7-45dc-b304-d7b0fa3c108f     2026-09-30  0.058761

[6760 rows x 3 columns]